import { after, describe, it } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs"; import { tmpdir } from "node:os"; import { join } from "node:path";
const dir = mkdtempSync(join(tmpdir(), "ima2-sprite-anchor-")); process.env.IMA2_CONFIG_DIR = dir; process.env.IMA2_DB_PATH = join(dir, "db.sqlite");
const db = await import("../lib/db.ts"); const { createAsset, deleteAsset } = await import("../lib/assetsStore.ts"); const { spriteRecipeStore } = await import("../lib/spriteRecipeStore.ts"); const { approveSpriteAnchor, requireApprovedSpriteAnchor, assertNoBaseReferenceAfterApproval } = await import("../lib/spriteAnchor.ts");
after(() => { db.closeDb(); rmSync(dir, { recursive: true, force: true }); });
const definition = { version: 1, character: { id: "hero", description: "hero", baseAssetId: null }, cell: { width: 64, height: 64, safeMarginX: 4, safeMarginY: 4 }, chromaKey: { name: "green", hex: "#00FF00", rgb: [0, 255, 0] }, states: [{ key: "idle", frames: 2, fps: 8, loop: true, action: "idle" }], style: "pixel" };
describe("sprite anchor policy", () => {
  it("requires an image and approved identity", async () => { const recipe = await spriteRecipeStore.create({ name: "Hero", recipe: definition }); await assert.rejects(requireApprovedSpriteAnchor(recipe.id), (error: any) => error.code === "ANCHOR_NOT_APPROVED"); const video = createAsset({ kind: "video", name: "clip" }); await assert.rejects(approveSpriteAnchor(recipe.id, video.id), (error: any) => error.code === "INVALID_ANCHOR_ASSET"); const image = createAsset({ kind: "image", name: "idle", filePath: "idle.png" }); assert.equal((await approveSpriteAnchor(recipe.id, image.id)).assetId, image.id); assert.equal((await requireApprovedSpriteAnchor(recipe.id)).assetId, image.id); deleteAsset(image.id); await assert.rejects(requireApprovedSpriteAnchor(recipe.id), (error: any) => error.code === "ANCHOR_NOT_APPROVED"); });
  it("forbids reattaching the base after approval", async () => { const base = createAsset({ kind: "image", name: "base" }); const recipe = await spriteRecipeStore.create({ name: "Base", recipe: { ...definition, character: { ...definition.character, baseAssetId: base.id } } }); const anchor = createAsset({ kind: "image", name: "anchor" }); const approved = await spriteRecipeStore.approveAnchor(recipe.id, anchor.id); assert.throws(() => assertNoBaseReferenceAfterApproval(approved, [{ role: "base", assetId: base.id }]), (error: any) => error.code === "BASE_REFERENCE_FORBIDDEN"); });
});
