import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import sharp from "sharp";
import { composeSpriteAtlas } from "../lib/spriteAtlasCompose.ts";

test("compose builds transparent atlas from curated frame order", async () => { const root = await mkdtemp(join(tmpdir(), "ima2-compose-")); try { const run = join(root, "sprite-runs", "r1"); const frames = join(run, "frames", "idle"); await mkdir(frames, { recursive: true }); await writeFile(join(frames, "frame-0.png"), await sharp({ create: { width: 4, height: 4, channels: 4, background: "red" } }).png().toBuffer()); await writeFile(join(frames, "frame-1.png"), await sharp({ create: { width: 4, height: 4, channels: 4, background: "blue" } }).png().toBuffer()); const manifest = { characterId: "x", engine: "sprite-gen", game_input: "x", degraded_static_fallback: false, curation_applied: false, frame_variant: "pixel", sprite_sheet_alpha: "atlas.png", sprite_sheet_alpha_report: "report.json", base_image: null, cell: {}, chroma_key: {}, animation: { cellWidth: 4, cellHeight: 4, columns: 2, rows: { idle: { row: 0, frames: 2, fps: 8, loop: true } } }, frame_layout: { sheetWidth: 8, sheetHeight: 4, cellWidth: 4, cellHeight: 4, rows: { idle: [{ x: 0, y: 0, w: 4, h: 4 }, { x: 4, y: 0, w: 4, h: 4 }] } } }; await writeFile(join(run, "manifest.json"), JSON.stringify(manifest)); const result = await composeSpriteAtlas({ generatedDir: root, runId: "r1" }); assert.equal(result.manifest.frame_layout.sheetWidth, 8); assert.deepEqual((await sharp(join(run, "atlas.png")).metadata()).width, 8); assert.equal((await readFile(join(frames, "frame-0.png"))).length > 0, true); } finally { await rm(root, { recursive: true, force: true }); } });
