import { after, describe, it } from "node:test"; import assert from "node:assert/strict"; import express from "express"; import { mkdtempSync, rmSync } from "node:fs"; import { tmpdir } from "node:os"; import { join } from "node:path";
const dir = mkdtempSync(join(tmpdir(), "ima2-sprite-routes-")); process.env.IMA2_CONFIG_DIR = dir; process.env.IMA2_DB_PATH = join(dir, "db.sqlite"); const db = await import("../lib/db.ts"); const { registerSpriteRecipeRoutes } = await import("../routes/spriteRecipes.ts"); after(() => { db.closeDb(); rmSync(dir, { recursive: true, force: true }); });
const definition = { version: 1, character: { id: "hero", description: "hero", baseAssetId: null }, cell: { width: 64, height: 64, safeMarginX: 4, safeMarginY: 4 }, chromaKey: { name: "green", hex: "#00FF00", rgb: [0, 255, 0] }, states: [{ key: "idle", frames: 2, fps: 8, loop: true, action: "idle" }], style: "pixel" };
async function withApp(run: (base: string) => Promise<void>) { const app = express(); app.use(express.json()); registerSpriteRecipeRoutes(app); const server = await new Promise<import("node:http").Server>((resolve) => { const value = app.listen(0, "127.0.0.1", () => resolve(value)); }); try { const address = server.address() as import("node:net").AddressInfo; await run(`http://127.0.0.1:${address.port}`); } finally { await new Promise<void>((resolve) => server.close(() => resolve())); } }
async function call(base: string, path: string, method = "GET", body?: unknown) { const response = await fetch(base + path, { method, headers: body === undefined ? undefined : { "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); return { response, body: await response.json() as any }; }
describe("sprite recipe routes", () => {
  it("supports create, list, get, patch and delete", async () => withApp(async (base) => { const made = await call(base, "/api/sprite-recipes", "POST", { name: "Hero", recipe: definition }); assert.equal(made.response.status, 201); const id = made.body.recipe.id; assert.equal((await call(base, "/api/sprite-recipes")).body.recipes.length, 1); assert.equal((await call(base, `/api/sprite-recipes/${id}`)).body.recipe.id, id); assert.equal((await call(base, `/api/sprite-recipes/${id}`, "PATCH", { name: "Hero 2" })).body.recipe.name, "Hero 2"); assert.deepEqual((await call(base, `/api/sprite-recipes/${id}`, "DELETE")).body, { ok: true }); assert.equal((await call(base, `/api/sprite-recipes/${id}`)).response.status, 404); }));
  it("returns the shared validation envelope", async () => withApp(async (base) => { const result = await call(base, "/api/sprite-recipes", "POST", { name: "bad", recipe: { ...definition, states: [] } }); assert.equal(result.response.status, 400); assert.equal(result.body.error.code, "INVALID_SPRITE_RECIPE"); assert.equal(typeof result.body.error.message, "string"); }));
});
