import { randomBytes } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Request, Response } from "express";
import { createAsset } from "./assetsStore.js";
import { errInfo } from "./errInfo.js";
import { generateMultimodeViaResponses } from "./responsesImageAdapter.js";
import { finishJob, INFLIGHT_RETRY_AFTER_SECONDS, isStartJobFailure, registerJobAbortController, startJob } from "./inflight.js";
import { requireApprovedSpriteAnchor } from "./spriteAnchor.js";
import { createSpriteJobEmitter, type SpriteJobEmitter } from "./spriteJobEvents.js";
import { renderSpriteLayoutGuide } from "./spriteLayoutGuide.js";
import { spriteRecipeStore, spriteStoreError, type SpriteRecipeRecord } from "./spriteRecipeStore.js";
import { buildSpriteRowPrompt } from "./spriteRowPrompt.js";
import type { RuntimeContext } from "./runtimeContext.js";

type Params = { id: string };
type Body = { states?: unknown; requestId?: unknown; async?: unknown; provider?: unknown; model?: unknown; quality?: unknown };
function requestId(req: Request): string { const raw = (req.body as Body)?.requestId; return typeof raw === "string" && raw.trim() ? raw.trim().slice(0, 200) : req.id || `sprite_${Date.now().toString(36)}`; }
function setSse(res: Response): void { res.setHeader("Content-Type", "text/event-stream; charset=utf-8"); res.setHeader("Cache-Control", "no-cache, no-transform"); res.setHeader("Connection", "keep-alive"); res.flushHeaders?.(); }
async function requireRecipe(id: string): Promise<SpriteRecipeRecord> { try { const recipe = await spriteRecipeStore.get(id); if (!recipe) throw spriteStoreError(404, "SPRITE_RECIPE_NOT_FOUND", "sprite recipe not found"); return recipe; } catch (error) { throw error; } }
function selectStates(recipe: SpriteRecipeRecord, raw: unknown) { if (raw === undefined) return recipe.recipe.states; if (!Array.isArray(raw) || raw.some((key) => typeof key !== "string")) throw spriteStoreError(400, "INVALID_SPRITE_RECIPE", "states must be an array of state keys"); const wanted = new Set(raw as string[]); const selected = recipe.recipe.states.filter((state) => wanted.has(state.key)); if (selected.length !== wanted.size) throw spriteStoreError(404, "SPRITE_STATE_NOT_FOUND", "sprite state not found"); return selected; }
async function references(recipe: SpriteRecipeRecord, guidePath: string, anchorMode: "base-idle-candidate" | "approved-anchor"): Promise<string[]> { try { const assetId = anchorMode === "approved-anchor" ? recipe.anchorAssetId : recipe.recipe.character.baseAssetId; if (!assetId) throw spriteStoreError(400, anchorMode === "approved-anchor" ? "ANCHOR_NOT_APPROVED" : "INVALID_ANCHOR_ASSET", "reference asset is required"); const row = (await import("./assetsStore.js")).getAsset(assetId); if (!row?.filePath || row.kind !== "image") throw spriteStoreError(400, "INVALID_ANCHOR_ASSET", "reference asset must be an image file"); const [identity, guide] = await Promise.all([readFile(join((await import("../config.js")).config.storage.generatedDir, row.filePath)), readFile(guidePath)]); return [`data:image/png;base64,${identity.toString("base64")}`, `data:image/png;base64,${guide.toString("base64")}`]; } catch (error) { throw error; } }
async function generateRow(input: { recipe: SpriteRecipeRecord; state: SpriteRecipeRecord["recipe"]["states"][number]; mode: "base-idle-candidate" | "approved-anchor"; requestId: string; ctx: RuntimeContext; signal: AbortSignal; events: SpriteJobEmitter; index: number; total: number; provider?: string | undefined; model?: string | undefined; quality?: string | undefined }) {
  try { await spriteRecipeStore.updateRow(input.recipe.id, input.state.key, { status: "running", requestId: input.requestId, errorCode: null }); input.events.emit("row", { requestId: input.requestId, recipeId: input.recipe.id, stateKey: input.state.key, rowIndex: input.index, totalRows: input.total, status: "running" }); const guide = await renderSpriteLayoutGuide({ recipeId: input.recipe.id, state: input.state, cell: input.recipe.recipe.cell, generatedDir: input.ctx.config.storage.generatedDir }); const refs = await references(input.recipe, join(input.ctx.config.storage.generatedDir, guide.relativePath), input.mode); const prompt = buildSpriteRowPrompt({ recipe: input.recipe.recipe, state: input.state, anchorMode: input.mode }); const result = await generateMultimodeViaResponses(input.provider ?? "auto", prompt, input.quality ?? "medium", `${guide.width}x${guide.height}`, "low", refs, input.requestId, "direct", input.ctx, { maxImages: 1, signal: input.signal, model: input.model }); const image = result.images[0]; if (!image?.b64) throw spriteStoreError(502, "SPRITE_ROW_EMPTY", "provider returned no sprite row"); const filename = `sprite_${input.recipe.id}_${input.state.key}_${randomBytes(4).toString("hex")}.png`; await mkdir(input.ctx.config.storage.generatedDir, { recursive: true }); await writeFile(join(input.ctx.config.storage.generatedDir, filename), Buffer.from(image.b64, "base64")); const asset = createAsset({ kind: "image", name: `${input.recipe.name} ${input.state.key}`, filePath: filename, metadata: { kind: "sprite-row", recipeId: input.recipe.id, stateKey: input.state.key, frames: input.state.frames, fps: input.state.fps, loop: input.state.loop, anchorAssetId: input.recipe.anchorAssetId, guide: guide.relativePath, requestId: input.requestId } }); if (input.mode === "base-idle-candidate") await spriteRecipeStore.setAnchorCandidate(input.recipe.id, asset.id); await spriteRecipeStore.updateRow(input.recipe.id, input.state.key, { status: "complete", resultAssetId: asset.id, requestId: input.requestId, errorCode: null }); input.events.emit("image", { requestId: input.requestId, recipeId: input.recipe.id, stateKey: input.state.key, assetId: asset.id, filename, url: `/generated/${filename}` }); return { stateKey: input.state.key, assetId: asset.id, status: "complete" }; } catch (error) { await spriteRecipeStore.updateRow(input.recipe.id, input.state.key, { status: input.signal.aborted ? "canceled" : "error", requestId: input.requestId, errorCode: input.signal.aborted ? "GENERATION_CANCELED" : ((error as { code?: string }).code ?? "SPRITE_ROW_FAILED") }); throw error; }
}
async function execute(req: Request<Params>, res: Response, ctx: RuntimeContext, anchorOnly: boolean): Promise<void> { const id = requestId(req); const body = req.body as Body; const asyncMode = body?.async === true; let owned = false; const controller = new AbortController(); const events = createSpriteJobEmitter(res, id); try { const recipe = await requireRecipe(req.params.id); const states = anchorOnly ? recipe.recipe.states.filter((state) => state.key === "idle").slice(0, 1) : selectStates(recipe, body?.states); if (!states.length) throw spriteStoreError(400, "SPRITE_STATE_NOT_FOUND", "idle state is required"); if (!anchorOnly) await requireApprovedSpriteAnchor(recipe.id); const started = startJob({ requestId: id, kind: "sprite-row", meta: { recipeId: recipe.id } }); if (started && isStartJobFailure(started)) { const status = started.code === "TOO_MANY_JOBS" ? 429 : 409; if (status === 429) res.setHeader("Retry-After", String(INFLIGHT_RETRY_AFTER_SECONDS)); throw spriteStoreError(status, started.code, started.code === "TOO_MANY_JOBS" ? "too many concurrent generation jobs" : "request id already in use"); } owned = true; registerJobAbortController(id, controller); if (asyncMode) res.status(202).json({ requestId: id }); else setSse(res); events.emit("phase", { requestId: id, recipeId: recipe.id, phase: "preparing", totalStates: states.length }); const rows = []; for (let index = 0; index < states.length; index++)  { const state = states[index]; if (!state) continue; rows.push(await generateRow({ recipe, state, mode: anchorOnly ? "base-idle-candidate" : "approved-anchor", requestId: id, ctx, signal: controller.signal, events, index, total: states.length, provider: typeof body.provider === "string" ? body.provider : undefined, model: typeof body.model === "string" ? body.model : undefined, quality: typeof body.quality === "string" ? body.quality : undefined })); } events.emit("done", { requestId: id, recipeId: recipe.id, requested: states.length, returned: rows.length, status: "complete", rows }); } catch (error) { const status = typeof (error as { status?: unknown }).status === "number" ? (error as { status: number }).status : 500; const code = controller.signal.aborted ? "GENERATION_CANCELED" : ((error as { code?: string }).code ?? "SPRITE_GENERATION_FAILED"); const payload = { requestId: id, recipeId: req.params.id, status, error: { code, message: errInfo(error).message } }; events.emit("error", payload); if (!res.headersSent) res.status(status).json(payload); } finally { if (owned) finishJob(id, { canceled: controller.signal.aborted }); events.end(); } }
export async function runSpriteAnchorGeneration(req: Request, res: Response, ctx: RuntimeContext): Promise<void> { try { await execute(req as Request<Params>, res, ctx, true); } catch (error) { if (!res.headersSent) res.status(500).json({ error: { code: "SPRITE_GENERATION_FAILED", message: errInfo(error).message } }); } }
export async function runSpriteRecipeGeneration(req: Request, res: Response, ctx: RuntimeContext): Promise<void> { try { await execute(req as Request<Params>, res, ctx, false); } catch (error) { if (!res.headersSent) res.status(500).json({ error: { code: "SPRITE_GENERATION_FAILED", message: errInfo(error).message } }); } }
