import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";
import type { SpriteCell, SpriteStateRecipe } from "./spriteRecipeSchema.js";
import { spriteStoreError } from "./spriteRecipeStore.js";

export interface SpriteLayoutGuide { stateKey: string; width: number; height: number; buffer: Buffer; relativePath: string; mime: "image/png" }
export function assertSpriteGuideGeometry(cell: SpriteCell, frames: number): void { if (!Number.isInteger(frames) || frames < 1 || frames > 12 || cell.width < 32 || cell.height < 32 || cell.safeMarginX * 2 >= cell.width || cell.safeMarginY * 2 >= cell.height || frames * cell.width * cell.height > 100_000_000) throw spriteStoreError(400, "INVALID_SPRITE_RECIPE", "invalid sprite guide geometry"); }
function guideSvg(cell: SpriteCell, frames: number, width: number): Buffer { const lines: string[] = []; for (let index = 0; index < frames; index++) { const x = index * cell.width; lines.push(`<rect x="${x + 1}" y="1" width="${cell.width - 2}" height="${cell.height - 2}" fill="none" stroke="#ffffff"/>`, `<rect x="${x + cell.safeMarginX}" y="${cell.safeMarginY}" width="${cell.width - cell.safeMarginX * 2}" height="${cell.height - cell.safeMarginY * 2}" fill="none" stroke="#ff00ff"/>`, `<line x1="${x + cell.width / 2}" y1="0" x2="${x + cell.width / 2}" y2="${cell.height}" stroke="#00ffff"/>`); } return Buffer.from(`<svg width="${width}" height="${cell.height}" xmlns="http://www.w3.org/2000/svg">${lines.join("")}</svg>`); }
export async function renderSpriteLayoutGuide(input: { recipeId: string; state: SpriteStateRecipe; cell: SpriteCell; generatedDir: string }): Promise<SpriteLayoutGuide> {
  try { assertSpriteGuideGeometry(input.cell, input.state.frames); if (!/^[A-Za-z0-9_-]+$/.test(input.recipeId) || !/^[A-Za-z0-9_-]+$/.test(input.state.key)) throw spriteStoreError(400, "INVALID_SPRITE_RECIPE", "recipe or state key contains invalid path characters"); const width = input.state.frames * input.cell.width; const relativePath = join("sprite-recipes", input.recipeId, "guides", `${input.state.key}.png`); const absolutePath = join(input.generatedDir, relativePath); await mkdir(join(input.generatedDir, "sprite-recipes", input.recipeId, "guides"), { recursive: true }); const buffer = await sharp({ create: { width, height: input.cell.height, channels: 4, background: input.cell ? { r: 0, g: 0, b: 0, alpha: 1 } : { r: 0, g: 0, b: 0, alpha: 1 } } }).composite([{ input: guideSvg(input.cell, input.state.frames, width) }]).png().toBuffer(); await sharp(buffer).toFile(absolutePath); return { stateKey: input.state.key, width, height: input.cell.height, buffer, relativePath, mime: "image/png" }; } catch (error) { if ((error as { status?: number }).status === 400) throw error; throw spriteStoreError(500, "SPRITE_GUIDE_WRITE_FAILED", "failed to write sprite layout guide"); }
}
