import { ulid } from "ulid";
import { getDb } from "./db.js";
import { normalizeSpriteRecipe, type SpriteAnchorStatus, type SpriteRecipeDefinition } from "./spriteRecipeSchema.js";

export type SpriteRowStatus = "pending" | "queued" | "running" | "complete" | "error" | "canceled";
export interface SpriteRecipeRowRecord { stateKey: string; status: SpriteRowStatus; requestId: string | null; resultAssetId: string | null; errorCode: string | null; updatedAt: number }
export interface SpriteRecipeRecord { id: string; name: string; recipe: SpriteRecipeDefinition; anchorAssetId: string | null; anchorStatus: SpriteAnchorStatus; rows: SpriteRecipeRowRecord[]; createdAt: number; updatedAt: number }
export interface CreateSpriteRecipeInput { name: unknown; recipe: unknown }
export interface UpdateSpriteRecipeInput { name?: unknown; recipe?: unknown }
export type SpriteRowPatch = Partial<Omit<SpriteRecipeRowRecord, "stateKey" | "updatedAt">>;
export interface SpriteRecipeStore { list(): Promise<SpriteRecipeRecord[]>; get(id: string): Promise<SpriteRecipeRecord | null>; create(input: CreateSpriteRecipeInput): Promise<SpriteRecipeRecord>; update(id: string, patch: UpdateSpriteRecipeInput): Promise<SpriteRecipeRecord>; setAnchorCandidate(id: string, assetId: string): Promise<SpriteRecipeRecord>; approveAnchor(id: string, assetId: string): Promise<SpriteRecipeRecord>; updateRow(id: string, stateKey: string, patch: SpriteRowPatch): Promise<void>; remove(id: string): Promise<void> }

type RecipeRow = { id: string; name: string; recipe: string; anchorAssetId: string | null; anchorStatus: SpriteAnchorStatus; createdAt: number; updatedAt: number };
type DbStateRow = { stateKey: string; status: SpriteRowStatus; requestId: string | null; resultAssetId: string | null; errorCode: string | null; updatedAt: number };
export function spriteStoreError(status: number, code: string, message: string): Error { const error = new Error(message) as Error & { status: number; code: string }; error.status = status; error.code = code; return error; }
function nameOf(value: unknown): string { const name = typeof value === "string" ? value.trim() : ""; if (!name || name.length > 120) throw spriteStoreError(400, "INVALID_SPRITE_RECIPE", "name must be 1-120 characters"); return name; }
const SELECT = "SELECT id, name, recipe, anchor_asset_id AS anchorAssetId, anchor_status AS anchorStatus, created_at AS createdAt, updated_at AS updatedAt FROM sprite_recipes";
function rowsFor(id: string): SpriteRecipeRowRecord[] { return getDb().prepare("SELECT state_key AS stateKey, status, request_id AS requestId, result_asset_id AS resultAssetId, error_code AS errorCode, updated_at AS updatedAt FROM sprite_recipe_rows WHERE recipe_id = ? ORDER BY rowid").all(id) as DbStateRow[]; }
function mapRow(row: RecipeRow): SpriteRecipeRecord { let recipe: SpriteRecipeDefinition; try { recipe = normalizeSpriteRecipe(JSON.parse(row.recipe)); } catch { throw spriteStoreError(500, "SPRITE_RECIPE_STORE_ERROR", `stored recipe is invalid: ${row.id}`); } const missingAnchor = row.anchorAssetId == null; return { ...row, recipe, anchorAssetId: row.anchorAssetId, anchorStatus: missingAnchor ? "missing" : row.anchorStatus, rows: rowsFor(row.id) }; }
function find(id: string): RecipeRow | undefined { return getDb().prepare(`${SELECT} WHERE id = ?`).get(id) as RecipeRow | undefined; }
function requireRecipe(id: string): RecipeRow { const row = find(id); if (!row) throw spriteStoreError(404, "SPRITE_RECIPE_NOT_FOUND", "sprite recipe not found"); return row; }
function syncRows(id: string, recipe: SpriteRecipeDefinition, now: number): void { const db = getDb(); const keys = recipe.states.map((state) => state.key); const insert = db.prepare("INSERT INTO sprite_recipe_rows (recipe_id, state_key, updated_at) VALUES (?, ?, ?) ON CONFLICT(recipe_id, state_key) DO NOTHING"); for (const key of keys) insert.run(id, key, now); if (keys.length) db.prepare(`DELETE FROM sprite_recipe_rows WHERE recipe_id = ? AND state_key NOT IN (${keys.map(() => "?").join(",")})`).run(id, ...keys); }

class SqliteSpriteRecipeStore implements SpriteRecipeStore {
  async list() { try { return (getDb().prepare(`${SELECT} ORDER BY updated_at DESC`).all() as RecipeRow[]).map(mapRow); } catch (error) { throw error; } }
  async get(id: string) { try { const row = find(id); return row ? mapRow(row) : null; } catch (error) { throw error; } }
  async create(input: CreateSpriteRecipeInput) { try { const recipe = normalizeSpriteRecipe(input.recipe); const id = `sr_${ulid()}`; const now = Date.now(); const db = getDb(); db.transaction(() => { db.prepare("INSERT INTO sprite_recipes (id,name,recipe,created_at,updated_at) VALUES (?,?,?,?,?)").run(id, nameOf(input.name), JSON.stringify(recipe), now, now); syncRows(id, recipe, now); })(); return mapRow(requireRecipe(id)); } catch (error) { throw error; } }
  async update(id: string, patch: UpdateSpriteRecipeInput) { try { const current = mapRow(requireRecipe(id)); const recipe = patch.recipe === undefined ? current.recipe : normalizeSpriteRecipe(patch.recipe); const name = patch.name === undefined ? current.name : nameOf(patch.name); const now = Date.now(); const db = getDb(); db.transaction(() => { db.prepare("UPDATE sprite_recipes SET name=?, recipe=?, updated_at=? WHERE id=?").run(name, JSON.stringify(recipe), now, id); syncRows(id, recipe, now); })(); return mapRow(requireRecipe(id)); } catch (error) { throw error; } }
  async setAnchorCandidate(id: string, assetId: string) { try { requireRecipe(id); const asset = getDb().prepare("SELECT kind FROM assets WHERE id=?").get(assetId) as { kind: string } | undefined; if (!asset || asset.kind !== "image") throw spriteStoreError(400, "INVALID_ANCHOR_ASSET", "anchor candidate must be an image"); getDb().prepare("UPDATE sprite_recipes SET anchor_asset_id=?, anchor_status='candidate', updated_at=? WHERE id=?").run(assetId, Date.now(), id); return mapRow(requireRecipe(id)); } catch (error) { throw error; } }
  async approveAnchor(id: string, assetId: string) { try { requireRecipe(id); const asset = getDb().prepare("SELECT kind FROM assets WHERE id=?").get(assetId) as { kind: string } | undefined; if (!asset) throw spriteStoreError(404, "ANCHOR_ASSET_NOT_FOUND", "anchor asset not found"); if (asset.kind !== "image") throw spriteStoreError(400, "INVALID_ANCHOR_ASSET", "anchor asset must be an image"); getDb().prepare("UPDATE sprite_recipes SET anchor_asset_id=?, anchor_status='approved', updated_at=? WHERE id=?").run(assetId, Date.now(), id); return mapRow(requireRecipe(id)); } catch (error) { throw error; } }
  async updateRow(id: string, stateKey: string, patch: SpriteRowPatch) { try { const current = mapRow(requireRecipe(id)); if (!current.recipe.states.some((state) => state.key === stateKey)) throw spriteStoreError(404, "SPRITE_STATE_NOT_FOUND", "sprite state not found"); getDb().prepare("UPDATE sprite_recipe_rows SET status=COALESCE(?,status), request_id=COALESCE(?,request_id), result_asset_id=COALESCE(?,result_asset_id), error_code=?, updated_at=? WHERE recipe_id=? AND state_key=?").run(patch.status ?? null, patch.requestId ?? null, patch.resultAssetId ?? null, patch.errorCode ?? null, Date.now(), id, stateKey); } catch (error) { throw error; } }
  async remove(id: string) { try { if (getDb().prepare("DELETE FROM sprite_recipes WHERE id=?").run(id).changes === 0) throw spriteStoreError(404, "SPRITE_RECIPE_NOT_FOUND", "sprite recipe not found"); } catch (error) { throw error; } }
}
export const spriteRecipeStore: SpriteRecipeStore = new SqliteSpriteRecipeStore();
