#!/usr/bin/env node
// Classify test files as runtime-importing vs source-text contract tests.
// Generates docs/migration/runtime-test-inventory.md.
//
// Flags:
//   --check             Fail if the on-disk inventory is stale.
//   --fail-js-runtime   Fail if any runtime-importing test is still .test.js
//                       (used after Phase 2 to lock the conversion in).

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const join = (...parts) => parts.join("/");

const check = process.argv.includes("--check");
const failJsRuntime = process.argv.includes("--fail-js-runtime");
const testDir = "tests";
const outPath = "docs/migration/runtime-test-inventory.md";

// Match imports of repo runtime surfaces: lib/, routes/, bin/, server.{ts,js}, config.{ts,js}.
const runtimeImportPattern =
  /(?:from\s+["']\.\.\/(?:lib|routes|bin)\/|from\s+["']\.\.\/(?:server|config)(?:\.(?:ts|js))?["']|import\(\s*["']\.\.\/(?:lib|routes|bin)\/|import\(\s*["']\.\.\/(?:server|config)(?:\.(?:ts|js))?["'])/;

const files = readdirSync(testDir)
  .filter((file) => /\.test\.[cm]?[jt]s$/.test(file))
  .sort();

const runtime = [];
const contract = [];

for (const file of files) {
  const path = join(testDir, file);
  const text = readFileSync(path, "utf8");
  (runtimeImportPattern.test(text) ? runtime : contract).push(path);
}

const renderList = (items) =>
  items.map((item) => `- \`${item}\``).join("\n") || "- _none_";
const output = [
  "# Runtime test migration inventory",
  "",
  "Generated by `npm run test:inventory` (script: `scripts/classify-tests.mjs`).",
  "",
  `_Tests considered "runtime-importing" if they import from \`../lib/\`, \`../routes/\`, \`../bin/\`, \`../server\`, or \`../config\`._`,
  "",
  `Total: ${files.length} (runtime: ${runtime.length}, contract: ${contract.length})`,
  "",
  "## Runtime-importing tests",
  renderList(runtime),
  "",
  "## Contract-only tests",
  renderList(contract),
  "",
].join("\n");

if (check) {
  const existing = existsSync(outPath) ? readFileSync(outPath, "utf8").replace(/\r\n/g, "\n") : null;
  if (existing !== output) {
    console.error(`${outPath} is stale. Run: node scripts/classify-tests.mjs`);
    process.exit(1);
  }
} else {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, output);
  console.log(`Wrote ${outPath} (${runtime.length} runtime / ${contract.length} contract).`);
}

if (failJsRuntime) {
  const jsRuntime = runtime.filter((path) => path.endsWith(".test.js"));
  if (jsRuntime.length > 0) {
    console.error("Runtime-importing tests must be .test.ts:");
    for (const path of jsRuntime) console.error(`- ${path}`);
    process.exit(1);
  }
}
