import { useI18n } from "../../i18n";
import type { SpriteRecipeDraft, SpriteRecipeFieldErrors } from "../../types/spriteRecipe";
export function SpriteRecipeForm({ draft, disabled, errors, onChange, onSubmit }: { draft: SpriteRecipeDraft; disabled: boolean; errors: SpriteRecipeFieldErrors; onChange(patch: Partial<SpriteRecipeDraft>): void; onSubmit(): void }) {
  const { t } = useI18n();
  const field = (key: "name" | "characterId" | "description" | "style" | "baseAssetId") => <label>{t(`sprite.recipe.${key}`)}<input value={draft[key]} disabled={disabled} aria-invalid={Boolean(errors[key as keyof SpriteRecipeFieldErrors])} onChange={(e) => onChange({ [key]: e.target.value })} />{errors[key as keyof SpriteRecipeFieldErrors] ? <span role="alert">{errors[key as keyof SpriteRecipeFieldErrors]}</span> : null}</label>;
  return <form className="sprite-recipe-form" onSubmit={(e) => { e.preventDefault(); onSubmit(); }}>
    {field("name")}{field("characterId")}{field("description")}{field("style")}{field("baseAssetId")}
    <fieldset><legend>{t("sprite.cell.title")}</legend>{(["width", "height", "safeMarginX", "safeMarginY"] as const).map((key) => <label key={key}>{t(`sprite.cell.${key}`)}<input type="number" min="0" value={draft.cell[key]} onChange={(e) => onChange({ cell: { ...draft.cell, [key]: Number(e.target.value) } })} /></label>)}</fieldset>
    <label>{t("sprite.chroma.hex")}<input type="color" value={draft.chroma.hex} onChange={(e) => onChange({ chroma: { ...draft.chroma, hex: e.target.value } })} /></label>
    <fieldset><legend>{t("sprite.states.title")}</legend>{draft.states.map((state, index) => <div className="sprite-state" key={`${state.key}-${index}`}><input aria-label={t("sprite.states.key")} value={state.key} onChange={(e) => onChange({ states: draft.states.map((s, i) => i === index ? { ...s, key: e.target.value } : s) })} /><input aria-label={t("sprite.states.frames")} type="number" min="1" value={state.frames} onChange={(e) => onChange({ states: draft.states.map((s, i) => i === index ? { ...s, frames: Number(e.target.value) } : s) })} /><button type="button" onClick={() => onChange({ states: draft.states.filter((_, i) => i !== index) })}>{t("sprite.states.remove")}</button></div>)}<button type="button" onClick={() => onChange({ states: [...draft.states, { key: "", frames: 4, fps: 8, loop: true, action: "" }] })}>{t("sprite.states.add")}</button></fieldset>
    <button className="assetgen-generate" disabled={disabled || !draft.name.trim() || !draft.characterId.trim()}>{disabled ? t("sprite.recipe.saving") : t("sprite.recipe.save")}</button>
  </form>;
}
