import type { GenerationErrorClass } from "./classes.js";

export const PROVIDER_ERROR_MAP = {
  MINIMAX_API_KEY_MISSING: "AUTH_INVALID",
  MINIMAX_AUTH_FAILED: "AUTH_INVALID",
  MINIMAX_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  MINIMAX_IMAGE_DOWNLOAD_FAILED: "NETWORK_FAILURE",
  MINIMAX_IMAGE_DOWNLOAD_TOO_LARGE: "CAPABILITY_UNSUPPORTED",
  MINIMAX_IMAGE_INVALID: "INTERNAL_STATE_ERROR",
  MINIMAX_INSUFFICIENT_BALANCE: "BILLING_REQUIRED",
  MINIMAX_MODEL_REQUIRES_REFERENCE: "CAPABILITY_UNSUPPORTED",
  MINIMAX_NETWORK_FAILED: "NETWORK_FAILURE",
  MINIMAX_NO_IMAGE: "INTERNAL_STATE_ERROR",
  MINIMAX_EMPTY_IMAGE: "INTERNAL_STATE_ERROR",
  MINIMAX_RATE_LIMITED: "RATE_LIMITED",
  MINIMAX_REF_TOO_MANY: "CAPABILITY_UNSUPPORTED",
  MINIMAX_SAFETY_BLOCKED: "CONTENT_REJECTED",
  MINIMAX_UPSTREAM_ERROR: "NETWORK_FAILURE",
  // Emitted by the shared routes rather than the adapter (routes/edit.ts).
  MINIMAX_MASK_UNSUPPORTED: "CAPABILITY_UNSUPPORTED",

  NAI_API_KEY_MISSING: "AUTH_INVALID",
  NAI_AUTH_FAILED: "AUTH_INVALID",
  // NovelAI answers 402 when the account has no active subscription, which is
  // a billing state rather than a bad token.
  NAI_SUBSCRIPTION_REQUIRED: "BILLING_REQUIRED",
  NAI_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  NAI_RATE_LIMITED: "RATE_LIMITED",
  NAI_UPSTREAM_ERROR: "NETWORK_FAILURE",
  NAI_EMPTY_IMAGE: "INTERNAL_STATE_ERROR",
  NAI_IMAGE_INVALID: "INTERNAL_STATE_ERROR",
  // The response container was not what the lane expects; see lib/naiZip.ts.
  NAI_RESPONSE_NOT_ZIP: "INTERNAL_STATE_ERROR",
  NAI_ZIP_INVALID: "INTERNAL_STATE_ERROR",
  NAI_ZIP_UNSUPPORTED: "INTERNAL_STATE_ERROR",
  NAI_ZIP_TOO_LARGE: "CAPABILITY_UNSUPPORTED",
  NAI_REF_UNSUPPORTED: "CAPABILITY_UNSUPPORTED",
  NAI_EDIT_UNSUPPORTED: "CAPABILITY_UNSUPPORTED",
  // Emitted by the shared routes rather than the adapter (routes/edit.ts).
  NAI_MASK_UNSUPPORTED: "CAPABILITY_UNSUPPORTED",

  GEMINI_API_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  GEMINI_API_KEY_MISSING: "AUTH_INVALID",
  GEMINI_API_NETWORK_FAILED: "NETWORK_FAILURE",
  GEMINI_API_NO_IMAGE: "INTERNAL_STATE_ERROR",
  GEMINI_API_RATE_LIMITED: "RATE_LIMITED",
  GEMINI_API_SAFETY_BLOCKED: "CONTENT_REJECTED",
  GEMINI_API_UPSTREAM_ERROR: "NETWORK_FAILURE",
  GEMINI_API_MASK_UNSUPPORTED: "CAPABILITY_UNSUPPORTED",

  GROK_AUTH_FAILED: "AUTH_INVALID",
  GROK_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  GROK_EMPTY_RESPONSE: "INTERNAL_STATE_ERROR",
  GROK_IMAGE_DOWNLOAD_FAILED: "NETWORK_FAILURE",
  GROK_IMAGE_TIMEOUT: "PROVIDER_TIMEOUT",
  GROK_NETWORK_FAILED: "NETWORK_FAILURE",
  GROK_PLANNER_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  GROK_PLANNER_EMPTY_TOOL_CALL: "INTERNAL_STATE_ERROR",
  GROK_PLANNER_INVALID_TOOL_ARGS: "INTERNAL_STATE_ERROR",
  GROK_PLANNER_NETWORK_FAILED: "NETWORK_FAILURE",
  GROK_PLANNER_TIMEOUT: "PROVIDER_TIMEOUT",
  GROK_RATE_LIMITED: "RATE_LIMITED",
  GROK_SEARCH_BAD_REQUEST: "CAPABILITY_UNSUPPORTED",
  GROK_SEARCH_EMPTY_RESPONSE: "INTERNAL_STATE_ERROR",
  GROK_SEARCH_NETWORK_FAILED: "NETWORK_FAILURE",
  GROK_SEARCH_TIMEOUT: "PROVIDER_TIMEOUT",
  GROK_UPSTREAM_ERROR: "NETWORK_FAILURE",
  GROK_VIDEO_DOWNLOAD_FAILED: "NETWORK_FAILURE",
  GROK_VIDEO_EMPTY_RESPONSE: "INTERNAL_STATE_ERROR",
  GROK_VIDEO_EXPIRED: "MODEL_UNAVAILABLE",
  GROK_VIDEO_FAILED: "INTERNAL_STATE_ERROR",
  GROK_VIDEO_AUDIO_TOO_MANY: "CAPABILITY_UNSUPPORTED",
  GROK_VIDEO_AUDIO_UNSUPPORTED_MODEL: "CAPABILITY_UNSUPPORTED",
  GROK_VIDEO_INVALID_MODE: "CAPABILITY_UNSUPPORTED",
  GROK_VIDEO_MODERATION_BLOCKED: "CONTENT_REJECTED",
  GROK_VIDEO_POLL_FAILED: "NETWORK_FAILURE",
  GROK_VIDEO_PLAN_TIMEOUT: "PROVIDER_TIMEOUT",
  GROK_VIDEO_REF_TOO_MANY: "CAPABILITY_UNSUPPORTED",
  GROK_VIDEO_REQUEST_FAILED: "CAPABILITY_UNSUPPORTED",
  GROK_VIDEO_TIMEOUT: "PROVIDER_TIMEOUT",
  GROK_VIDEO_FRAME_FAILED: "INTERNAL_STATE_ERROR",
  GROK_VIDEO_INVALID_PROMPT: "CAPABILITY_UNSUPPORTED",
  GROK_MASK_UNSUPPORTED: "CAPABILITY_UNSUPPORTED",
  GROK_REF_TOO_MANY: "CAPABILITY_UNSUPPORTED",

  AGY_ARTIFACT_NOT_FOUND: "INTERNAL_STATE_ERROR",
  AGY_GENERATION_FAILED: "INTERNAL_STATE_ERROR",
  AGY_MALFORMED_RESULT: "INTERNAL_STATE_ERROR",
  AGY_PARSE_FAILED: "INTERNAL_STATE_ERROR",
  AGY_PATH_REJECTED: "INTERNAL_STATE_ERROR",
  AGY_PROCESS_ERROR: "NETWORK_FAILURE",
  AGY_QUOTA_EXHAUSTED: "RATE_LIMITED",
  AGY_TIMEOUT: "PROVIDER_TIMEOUT",
  AGY_MASK_UNSUPPORTED: "CAPABILITY_UNSUPPORTED",
  AGY_REF_TOO_MANY: "CAPABILITY_UNSUPPORTED",
  AGY_VIDEO_UNSUPPORTED: "CAPABILITY_UNSUPPORTED",

  ATLASCLOUD_API_KEY_MISSING: "AUTH_INVALID",
  ATLASCLOUD_GENERATE_FAILED: "NETWORK_FAILURE",
  ATLASCLOUD_GENERATION_FAILED: "INTERNAL_STATE_ERROR",
  ATLASCLOUD_NO_PREDICTION_ID: "INTERNAL_STATE_ERROR",
  ATLASCLOUD_OUTPUT_DOWNLOAD_FAILED: "NETWORK_FAILURE",
  ATLASCLOUD_REF_TOO_MANY: "CAPABILITY_UNSUPPORTED",
  ATLASCLOUD_UPLOAD_FAILED: "NETWORK_FAILURE",
  ATLASCLOUD_MASK_UNSUPPORTED: "CAPABILITY_UNSUPPORTED",
  ATLASCLOUD_UPLOAD_NO_URL: "INTERNAL_STATE_ERROR",
} as const satisfies Record<string, GenerationErrorClass>;

export type ProviderErrorCode = keyof typeof PROVIDER_ERROR_MAP;

export type DynamicProviderCodeSite = {
  file: string;
  prefixVariable: string;
  prefixDomain: readonly string[];
  suffix: string;
  expandedCodes: readonly ProviderErrorCode[];
};

export const DYNAMIC_PROVIDER_CODE_SITES = [{
  file: "lib/grokImageCore.ts",
  prefixVariable: "prefix",
  prefixDomain: ["GROK_SEARCH", "GROK_PLANNER"],
  suffix: "BAD_REQUEST",
  expandedCodes: ["GROK_SEARCH_BAD_REQUEST", "GROK_PLANNER_BAD_REQUEST"],
}] as const satisfies readonly DynamicProviderCodeSite[];

/**
 * Codes whose meaning depends on the HTTP status the adapter attached, so a
 * single static class would be wrong. GROK_VIDEO_REQUEST_FAILED covers
 * 400/403/412 rejections AND upstream 5xx/network failures
 * (lib/grokVideoShared.ts, lib/grokVideoAdapter.ts); AtlasCloud upload and
 * generation codes likewise carry arbitrary upstream statuses.
 */
const STATUS_DEPENDENT_CODES: Record<string, { clientError: GenerationErrorClass; serverError: GenerationErrorClass }> = {
  GROK_VIDEO_REQUEST_FAILED: { clientError: "CAPABILITY_UNSUPPORTED", serverError: "NETWORK_FAILURE" },
  ATLASCLOUD_UPLOAD_FAILED: { clientError: "CAPABILITY_UNSUPPORTED", serverError: "NETWORK_FAILURE" },
  // GENERATE_FAILED forwards the upstream HTTP status
  // (lib/atlasCloudImageAdapter.ts:121). GENERATION_FAILED is a fixed 502 poll
  // failure (lib/atlasCloudImageAdapter.ts:158) and stays statically mapped.
  ATLASCLOUD_GENERATE_FAILED: { clientError: "CAPABILITY_UNSUPPORTED", serverError: "NETWORK_FAILURE" },
};

export function providerErrorClass(code: unknown, status?: unknown): GenerationErrorClass | undefined {
  if (typeof code !== "string") return undefined;
  const statusDependent = STATUS_DEPENDENT_CODES[code];
  if (statusDependent) {
    const numeric = Number(status);
    // 429 is a rate limit regardless of which family it arrives through.
    if (numeric === 429) return "RATE_LIMITED";
    if (Number.isFinite(numeric) && numeric >= 400 && numeric < 500) return statusDependent.clientError;
    return statusDependent.serverError;
  }
  return (PROVIDER_ERROR_MAP as Record<string, GenerationErrorClass>)[code];
}
